-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "bio" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "countryScope" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "coreFocus" TEXT;
