-- AlterTable
ALTER TABLE "Report" ADD COLUMN IF NOT EXISTS "type" TEXT NOT NULL DEFAULT 'monthly';
ALTER TABLE "Report" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'approved';
ALTER TABLE "Report" ADD COLUMN IF NOT EXISTS "content" TEXT;
ALTER TABLE "Report" ADD COLUMN IF NOT EXISTS "periodStart" TIMESTAMP(3);
ALTER TABLE "Report" ADD COLUMN IF NOT EXISTS "periodEnd" TIMESTAMP(3);
ALTER TABLE "Report" ADD COLUMN IF NOT EXISTS "projectId" TEXT;
ALTER TABLE "Report" ADD COLUMN IF NOT EXISTS "submittedById" TEXT;
ALTER TABLE "Report" ADD COLUMN IF NOT EXISTS "approvedById" TEXT;
ALTER TABLE "Report" ADD COLUMN IF NOT EXISTS "submittedAt" TIMESTAMP(3);
ALTER TABLE "Report" ADD COLUMN IF NOT EXISTS "approvedAt" TIMESTAMP(3);
ALTER TABLE "Report" ADD COLUMN IF NOT EXISTS "rejectedAt" TIMESTAMP(3);
ALTER TABLE "Report" ADD COLUMN IF NOT EXISTS "rejectionReason" TEXT;
ALTER TABLE "Report" ADD COLUMN IF NOT EXISTS "reviewerNotes" TEXT;
ALTER TABLE "Report" ADD COLUMN IF NOT EXISTS "incidentSeverity" TEXT;
ALTER TABLE "Report" ADD COLUMN IF NOT EXISTS "incidentLocation" TEXT;
ALTER TABLE "Report" ADD COLUMN IF NOT EXISTS "actionsTaken" TEXT;
ALTER TABLE "Report" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AddForeignKey
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'Report_projectId_fkey') THEN
    ALTER TABLE "Report" ADD CONSTRAINT "Report_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'Report_submittedById_fkey') THEN
    ALTER TABLE "Report" ADD CONSTRAINT "Report_submittedById_fkey" FOREIGN KEY ("submittedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'Report_approvedById_fkey') THEN
    ALTER TABLE "Report" ADD CONSTRAINT "Report_approvedById_fkey" FOREIGN KEY ("approvedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;
